FROM python:3.7-slim-buster
MAINTAINER asi@dbca.wa.gov.au
RUN apt-get update -y \
  && apt-get upgrade -y \
  && apt-get install --no-install-recommends -y gdal-bin proj-bin \
  && rm -rf /var/lib/apt/lists/* \
  && pip install --upgrade pip
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ingester.py utils.py ./
CMD ["python", "ingester.py"]
