FROM python:3.9.12-slim-bullseye
MAINTAINER asi@dbca.wa.gov.au
LABEL org.opencontainers.image.source https://github.com/dbca-wa/cddp-ingester
RUN apt-get update -y \
  && apt-get upgrade -y \
  && apt-get install --no-install-recommends -y gdal-bin proj-bin \
  && rm -rf /var/lib/apt/lists/* \
  && pip install --upgrade pip
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ingester.py monitor.py utils.py ./
CMD ["python", "ingester.py"]
